#=========================== Filebeat inputs =============================
filebeat.inputs:

- type: log
  enabled: true
  encoding: utf-8
  paths:
    - /data/report/report_new*.log

  scan_frequency: 2s
  harvester_buffer_size: 20971520
  max_bytes: 20971520
  tail_files: false
  backoff: 1s
  max_backoff: 10s

  close_inactive: 6h
  clean_inactive: 72h
  ignore_older: 70h
  close_timeout: 6h

- type: log
  enabled: true
  encoding: utf-8
  paths:
    - /data/report/report_old*.log

  scan_frequency: 2s
  harvester_buffer_size: 10485760
  max_bytes: 10485760
  tail_files: false
  backoff: 1s
  max_backoff: 10s

  close_inactive: 6h
  clean_inactive: 72h
  ignore_older: 70h
  close_timeout: 6h

- type: log
  enabled: true
  encoding: utf-8
  paths:
    - /data/report/report_monitor*.log

  scan_frequency: 2s
  harvester_buffer_size: 10485760
  max_bytes: 10485760
  tail_files: false
  backoff: 1s
  max_backoff: 10s

  close_inactive: 6h
  clean_inactive: 72h
  ignore_older: 70h
  close_timeout: 6h

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3

#================================ General =====================================
filebeat.registry_file: /data/filebeat/data/registry-api.index
filebeat.registry_file_permissions: 0644
max_procs: 5
path.home: /etc/filebeat
path.config: /etc/filebeat

path.data: /data/filebeat/data
path.logs: /data/filebeat/logs

queue.mem.events: 40960
queue.mem.flush.min_events: 1024
queue.mem.flush.timeout: 2s

#================================ Outputs =====================================
output.redis:
  enable: true
  hosts: ['192.168.1.1:6379', '192.168.1.2:6379', '192.168.1.3:6379']
  loadbalance: true
  worker: 2
  datatype: list
  keys:
    - key: "wkread_report_new_dadianlog_queue"
      when.contains:
        source: "report_new"
    - key: "wkread_report_old_dadianlog_queue"
      when.contains:
        source: "report_old"
    - key: "wkread_report_monitor_dadianlog_queue"
      when.contains:
        source: "report_monitor"

  db: 0
  timeout: 2

logging.level: info
logging.to_files: true
logging.files:
  path: /data/filebeat/logs
  name: filebeat-api.log
  keepfiles: 7
  rotateeverybytes: 104857600
  interval: 24h
  permissions: 0644

