#=========================== Filebeat inputs =============================
filebeat.inputs:

- type: log
  enabled: true
  encoding: utf-8
  paths:
    - /data/app/logs/novel-rec/common-default.log
    - /data/app/logs/novel-rec/novelrec-biz.log

  scan_frequency: 2s
  harvester_buffer_size: 20971520
  max_bytes: 20971520
  tail_files: false
  backoff: 1s
  max_backoff: 10s

  close_inactive: 6h
  clean_inactive: 72h
  ignore_older: 70h
  close_timeout: 6h


#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3

#================================ General =====================================
filebeat.registry.path: /data/filebeat/data
max_procs: 5
path.home: /etc/filebeat
path.config: /etc/filebeat

path.data: /data/filebeat/data
path.logs: /data/filebeat/logs

queue.mem.events: 40960
queue.mem.flush.min_events: 1024
queue.mem.flush.timeout: 2s

#================================ Outputs =====================================
output.logstash:
  hosts: ["192.168.1.1:5044", "192.168.1.2:5044", "192.168.1.3:5044"]


logging.level: info
logging.to_files: true
logging.files:
  path: /data/filebeat/logs
  name: filebeat-novelrec.log
  keepfiles: 7
  rotateeverybytes: 104857600
  interval: 24h
  permissions: 0644

